project_id = "awgseqiufhqwxmihfcnd"

[functions.fetch-articles]
verify_jwt = false

[functions.generate-digest]
verify_jwt = false

[functions.eia-rates]
verify_jwt = false

[functions.pvwatts-states]
verify_jwt = false
